### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '...AIC22_Track1_MTMC_ID10/datasets/AIC22_Track1_MTMC_Tracking/test/images/test/S06/c044/img1'

### ISSUE THREAD

**Issue by deanofthewebb** [royukira/AIC22_Track1_MTMC_ID10#3]
Thanks for your work! When attempting to run the intermediate results, I downloaded the intermediate dataset, however it does not include the DATA_DIR used in `./run_mtmc.sh` Can you please include this data so the program can execcute successfully?

Here's the StackTrace:
```
[Err]: invalid source root: .../datasets/AIC22_Track1_MTMC_Tracking/test/
Done
tracking c041 with temp_aic_all.yml
tracking c042 with temp_aic_all.yml
tracking c044 with temp_aic_all.yml
tracking c045 with temp_aic_all.yml
tracking c043 with temp_aic_all.yml
tracking c046 with temp_aic_all.yml
Is use embedding distance? False
Traceback (most recent call last):
  File ".../tracker/ByteTrack/src/fair_app.py", line 324, in <module>
    run(
  File ".../tracker/ByteTrack/src/fair_app.py", line 178, in run
    seq_info = gather_sequence_info(sequence_dir, detection_file, max_frame_idx)
  File ".../tracker/ByteTrack/src/fair_app.py", line 50, in gather_sequence_info
    for f in os.listdir(image_dir)}
FileNotFoundError: [Errno 2] No such file or directory: '.../datasets/AIC22_Track1_MTMC_Tracking/test/images/test/S06/c041/img1'
```

**Comment by royukira** [comment]
@deanofthewebb Sorry, the problem is caused by missing the step of generating images from video stream. I have corrected it in the latest version. Please pull the latest version [56695d8](https://github.com/royukira/AIC22_Track1_MTMC_ID10/commit/56695d8162be360349c36522ed2901b0473c0b69) and try it again. 

Or you can add the below script commands to the `./run_mtmc.sh`.
```
# Add this
cd ../detector/
python gen_images_aic.py ${MCMT_CONFIG_FILE}

# # # # #### ByteTrack with occlusion handling. ####
cd ../tracker/ByteTrack
bash run_aic.sh ${MCMT_CONFIG_FILE}
wait
```

Hope this can help you.
